import Head from "next/head";
import React from "react";
import Header from "./Header";

const Layout = () => {
  return (
    <>
      <Head>
        <title>Demo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
    </>
  );
};

export default Layout;
